// Code generated by MockGen. DO NOT EDIT.
// Source: env.go
//
// Generated by this command:
//
//	mockgen -source=env.go -destination=mocks/mock-env.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUnmarshaler is a mock of Unmarshaler interface.
type MockUnmarshaler struct {
	ctrl     *gomock.Controller
	recorder *MockUnmarshalerMockRecorder
	isgomock struct{}
}

// MockUnmarshalerMockRecorder is the mock recorder for MockUnmarshaler.
type MockUnmarshalerMockRecorder struct {
	mock *MockUnmarshaler
}

// NewMockUnmarshaler creates a new mock instance.
func NewMockUnmarshaler(ctrl *gomock.Controller) *MockUnmarshaler {
	mock := &MockUnmarshaler{ctrl: ctrl}
	mock.recorder = &MockUnmarshalerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnmarshaler) EXPECT() *MockUnmarshalerMockRecorder {
	return m.recorder
}

// UnmarshalEnvironmentValue mocks base method.
func (m *MockUnmarshaler) UnmarshalEnvironmentValue(data string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnmarshalEnvironmentValue", data)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnmarshalEnvironmentValue indicates an expected call of UnmarshalEnvironmentValue.
func (mr *MockUnmarshalerMockRecorder) UnmarshalEnvironmentValue(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnmarshalEnvironmentValue", reflect.TypeOf((*MockUnmarshaler)(nil).UnmarshalEnvironmentValue), data)
}

// MockMarshaler is a mock of Marshaler interface.
type MockMarshaler struct {
	ctrl     *gomock.Controller
	recorder *MockMarshalerMockRecorder
	isgomock struct{}
}

// MockMarshalerMockRecorder is the mock recorder for MockMarshaler.
type MockMarshalerMockRecorder struct {
	mock *MockMarshaler
}

// NewMockMarshaler creates a new mock instance.
func NewMockMarshaler(ctrl *gomock.Controller) *MockMarshaler {
	mock := &MockMarshaler{ctrl: ctrl}
	mock.recorder = &MockMarshalerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMarshaler) EXPECT() *MockMarshalerMockRecorder {
	return m.recorder
}

// MarshalEnvironmentValue mocks base method.
func (m *MockMarshaler) MarshalEnvironmentValue() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarshalEnvironmentValue")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarshalEnvironmentValue indicates an expected call of MarshalEnvironmentValue.
func (mr *MockMarshalerMockRecorder) MarshalEnvironmentValue() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarshalEnvironmentValue", reflect.TypeOf((*MockMarshaler)(nil).MarshalEnvironmentValue))
}
